version: '3.7'
services:
  postgres:
    image: postgres:14
    restart: always
    container_name: "postgres_user"
    ports:
        - 54322:5432
    environment:
      PGUSER: postgres
      PGPASSWORD:
      POSTGRES_PASSWORD:
      POSTGRES_USER: postgres
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
